# (PART\*) Bringing Your Own Data {-}


```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```
# Uploading From Your Local Computer

In this example, we'll upload some genomic data that is stored on your local computer. You can use a file of your own, or download the files we are using in this example.

TODO: Add information about what the data is

## Step One: Create a Workspace

The starting point for bringing your own data to AnVIL is the Workspace. Before you can do anything, you will need to create a workspace. Once you have logged into your AnVIL account, click on Workspaces in the left-side menu. You can open this menu by clicking the three line icon in the upper left hand corner.

TODO: Add image about creating workspace

Once you have opened the Workspace page, create a new workspace by clicking on the plus sign at the top.

TODO: Add image about creating workspace

You should now see a pop-up window that lets you customize your new workspace. You will need to give your new workspace a unique name and assign it to a billing project. The "anvil-outreach" billing project is used here as an example, but you will not be able to assign it. You'll have to use one of your own billing projects. After filling out these two fields, click the "Quick Create Workspace" button to create a workspace without enabling sharing or additional security options.

TODO: Add image about creating workspace

You can read about Authorization Domains for workspace security in [this article](https://support.terra.bio/hc/en-us/articles/8527464803739-How-to-set-up-and-use-an-Authorization-Domain) at the AnVIL Portal.

Once you have created a workspace, AnVIL will take you to the Workspace Dashboard.

## Open the Data Uploader

When you switch to the Data tab in your Workspace, you'll see three headers on the left hand side: **TABLES**, **REFERENCE DATA**, and **WORKSPACE DATA**. At the moment all three of these sections are empty. We will use the Data Uploader tool to populate the **TABLES** and **WORKSPACE DATA** sections of the Workspace.

Click on the box in the upper left hand corner that says "Import Data". From the dropdown menu, you'll want to choose "Open data uploader".

TODO: Add image

## Create a data collection

## Upload data collection

## Upload data table with metadata

## Verify files were moved into your workspace
